### ISSUE TITLE
训练2类目标

### ISSUE THREAD

**Issue by wait1988** [eric612/Caffe-YOLOv3-Windows#10]
你好，请问用yolov3_lite训练两类目标的时候，网络配置文件该如何修改呢？
我改了conv20,conv21的num_output为18
Yolov3Loss1，Yolov3Loss2的num_class为2
训练报错：
yolov3_layer.cpp:143] Check failed: input_count == tmp_input_count (6498 vs. 7581)
求正确的改法~

**Comment by eric612** [comment]
@wait1988 
num_output 應為 (4+1+2)*3 = 21

**Comment by wait1988** [comment]
@eric612 谢谢 傻了我 手误。。。

**Comment by 18022443868** [comment]
目标探测训练2类，Check failed: input_count == tmp_input_count (27075 vs. 7581)，感觉num_output 有好几处，都要进行修改？
