### ISSUE TITLE
yolov3 lite训练的一些疑惑

### ISSUE THREAD

**Issue by wait1988** [eric612/Caffe-YOLOv3-Windows#12]
1.batch size设为6，是不是太小了？对caffe不熟，batch size=6,iter_size=4,那么每次训练的样本数是int(6/4)?
2.多个resize_param，到底用的哪一个？是不是没有实现多尺度训练？我看显存占用一直没变。

**Comment by eric612** [comment]
1. 如果pre-train weight使用 imagenet model ，batch size 就要用到64 ，設24(batch size * iter_size)是因為pretrain weights 是 mobilenet-ssd coco weights，不需要使用太大的batch size，增加收斂速度，當然設大一點精準度還是會提升
2. 每個resize param 下都有一個Prob ，預設是10個batch每個機率都是0.1，顯存占用不會變是因為初始化時就直接佔用最大空間 (608*608)

**Comment by wait1988** [comment]
OK,thx.
